"vsetvli t0, x0, e16 ,m2 ;"
"vle16.v v0, (%[h]) ;"
"vle16.v v4, (%[x]) ;"
"vadd.vv v8, v0, v4 ;"
"vse16.v v8, (%[y]) ;"
"addi %[arith_cnt], %[arith_cnt], 1 ;"
"addi %[lw_cnt], %[lw_cnt], 2;"
"addi %[sw_cnt], %[sw_cnt], 1;"
"addi %[others_cnt], %[others_cnt], 1;"